baseURL = "https://ragibasif.github.io/"
languageCode = "en-us"
title = "Ragib Asif"

[params]
  author = "Ragib Asif"
  description = "Personal website of Ragib Asif"
  github = "https://github.com/ragibasif"
  linkedin = "https://www.linkedin.com/in/ragibasif"
  youtube = "https://www.youtube.com/@ragib_asif"
  email = "ragibasif@tuta.io"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Archive"
    url = "/archive/"
    weight = 2
  [[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

