baseURL = "https://ragibasif.github.io/"
languageCode = "en-us"
title = "Ragib Asif"

[params]
  author = "Ragib Asif"
  description = "A minimal blog and portfolio"
  github = "https://github.com/ragibasif"
  linkedin = "https://www.linkedin.com/in/ragibasif"
  youtube = "https://www.youtube.com/@ragib_asif"
  email = "ragibasif@tuta.io"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

